build:
    environment:
        python: 3.6.0
    tests:
        override:
            - echo OK
filter:
    excluded_paths:
        - '*'

checks:
    python:
        code_rating: true
        duplicate_code: true
        classes_valid_slots: true
