resources:
  - name: ci_skip_gitRepo
    type: GitRepo
    configuration:
      gitProvider: GitHub
      path: srz-zumix/ci-skip
      branches:
        include: master|^feature/.*|^jfrog/.*
  - name: ci_skip_cron_trigger
    type: CronTrigger
    configuration:
      interval: '0 0 * * 2'

pipelines:
  - name: ci_skip
    steps:
      - name: spec
        type: Bash
        configuration:
          inputResources:
            - name: ci_skip_gitRepo
        execution:
          onStart:
          - update_commit_status ci_skip_gitRepo # Status: "processing"
          onExecute:
            - update_commit_status ci_skip_gitRepo # Status: "processing"
            - pushd ${res_ci_skip_gitRepo_resourcePath}
            - echo OK
            - popd
          onFailure:
            - update_commit_status ci_skip_gitRepo # Status: "failure"
          onSuccess:
            - update_commit_status ci_skip_gitRepo # Status: "success"
  - name: ci_skip_noop
    steps:
      - name: noop
        type: Bash
        configuration:
          inputResources:
            - name: ci_skip_cron_trigger
        execution:
          onExecute:
            - echo Hello
