language: python
python: 2.7

build:
  ci:
    - echo OK

jobs:
  - name: test
    type: runSh
    steps:
      - IN: ci-skip_runCI
      - TASK:
          script:
            - echo "test..."
  - name: project_build_prepare
    type: runSh
    steps:
      - IN: ci-skip_gitRepo
      - TASK:
          script:
            - echo "Preparing your build..."
      - OUT: ci-skip_ciRepo
        replicate: ci-skip_gitRepo