version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:cosmic-browsers
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
